#include "../../skynet/src/skynet/checkers.hpp"
#include "../../skynet/src/skynet/checkers_client.hpp"
// skynet::checkers::play_game
// skynet::checkers::print_game
// skynet::checkers::game_info
// skynet::checkers::game_info_t
#include "checkers_skynet_interface.h"
#include "json.hpp"
using ai::CheckersSkynetInterface;
#include "checkers-game.h"
using ai::CheckersGame;
